<!-- <script setup lang="ts">
</script>
<template>
  <div>
    <div class="mx-28 mt-24 grid gap-7">
      <div class="text-center text-4xl text-orange-500">Benefits</div>
      <div class="flex items-center">
        <img src="@/assets/img/service/low-cost.jpeg" width="135" class="rounded-full" alt="">
        <div class="w-64 h-1 bg-orange-500"></div>
        <div class="px-7">
          <div class="text-black text-xl">Ease of Formation and Low Cost</div>
          <div class="px-4">
            
            Proprietorship registration is relatively straightforward, with minimal legal formalities and documentation
            required. This simplicity reduces both the time and cost associated with starting a business.
          </div>
        </div>
      </div>
      <div class="flex items-center">
        <img src="@/assets/img/service/control.jpeg" width="135" class="rounded-full" alt="">
        <div class="w-64 h-1 bg-orange-500"></div>
        <div class="px-7">
          <div class="text-black text-xl">Complete Control</div>
          <div class="px-4">
       
            As the sole owner, you have full control over all business decisions, including management, operations, and
            strategic planning. This autonomy allows for quick decision-making without needing to consult others.
          </div>
        </div>
      </div>
      <div class="flex items-center">
        <img src="@/assets/img/service/tax.jpeg" width="135" class="rounded-full" alt="">
        <div class="w-64 h-1 bg-orange-500"></div>
        <div class="px-7">
          <div class="text-black text-xl">Tax Benefits</div>
          <div class="px-4">
         
            Proprietors often benefit from simplified tax processes. Income from the business is typically taxed as
            personal income, which can lead to lower tax rates and eligibility for various deductions that apply to
            individuals.
          </div>
        </div>
      </div>
      <div class="flex items-center">
        <img src="@/assets/img/service/privacy.jpeg" width="135" class="rounded-full" alt="">
        <div class="w-64 h-1 bg-orange-500"></div>
        <div class="px-7">
          <div class="text-black text-xl">Privacy of Business Affairs</div>
          <div class="px-4">
            
            Since a proprietorship is not required to publicly disclose its financials or other business details, the
            owner maintains a higher level of privacy compared to other business structures, such as corporations.
          </div>
        </div>
      </div>
      <div class="flex items-center">
        <img src="@/assets/img/service/direct-claim.jpeg" width="135" class="rounded-full" alt="">
        <div class="w-64 h-1 bg-orange-500"></div>
        <div class="px-7">
          <div class="text-black text-xl">Direct Claim to Profits</div>
          <div class="px-4">
  
            All profits generated by the business go directly to the owner. There is no need to share profits with
            partners or shareholders, allowing the proprietor to reinvest or use the earnings as they see fit.
          </div>
        </div>
      </div>
    </div>
    <div>
      <div class="mx-28 my-12">
        <div>
            <img src="@/assets/img/service/direct-claim.jpeg" class="" alt="">
        </div>
      </div>
    </div>
  </div>
</template> -->
<template>
    <div class="p-32 flex flex-col justify-center items-center text-center">
        <iframe class="w-full h-96 -mt-20" src="https://lottie.host/embed/1886f40d-81ca-415d-ba3f-c2bc83f5ca3b/DYRHFv0KTt.json"></iframe>
        <div class="text-2xl text-red-900">Webpage Under Construction</div>
    </div>
</template>